server:
  port: 1001
  
#spring.profiles.active=native提供本地存储配置
#也可以通过spring.cloud.config.server.native.searchLocations=file:F:/properties/属性来指定配置文件的位置

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://git.coding.net/xjp-dream/spring-cloud-7simple.git
          search-paths:
          - cloud-config-repo
          username: xjpdyx@hotmail.com
          password: xjpdyx32.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
          
