server:
  port: 8762
spring:
  application:
    name: gateway-server
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/
zuul:
  routes:
    cmsBook: /cmsBook/**
    bookhouse: /bookhouse/**

