server:
  port: 1003
eureka:
  client:
    service-url:
      defaultZone: http://192.168.43.131:1000/eureka/
spring:
  application:
    name: authc-client
  thymeleaf:
    #修改跳转的前缀和后缀,以下注释部分是spring boot的默认配置
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    #开发过程中需将缓存关闭
    cache: false
    check-template: false
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    host: 192.168.43.131
    port: 6379
    password:
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      #连接池中最大空闲连接
      max-idle: 8
      #连接池中最小空闲连接
      min-idle: 1
    #连接超时时间（毫秒）
    timeout: 0