spring:
  application:
    name: cmsBook
  http:
    multipart:
      max-file-size: 2000Mb
      max-request-size: 2500Mb
  thymeleaf:
      #修改跳转的前缀和后缀,以下注释部分是spring boot的默认配置
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      #开发过程中需将缓存关闭
      cache: false
      check-template: false
server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/

