spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    #是否将自己注册到Eureka，默认为true
    register-with-eureka: false
    #是否从Eureka Server获取注册信息，默认为true
    fetch-registry: false
    service-url:
      #与Eureka Server交互地址，多个用，分隔
      defaultZone: http://localhost:8761/eureka/
    #健康检查
    healthcheck:
      enabled: true
  server:
    #关闭自我保护
    enable-self-preservation: false

#高可用的eureka集群配置认证会出现登录不了的情况
security:
  basic:
    #开启基于HTTP basic的认证
    enabled: true
  user:
    #配置登录的账号是user
    name: admin
    password: 123456
