#服务器配置
server:
  port: 8000
spring:
  application:
    name: ancient
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/ancient?useSSL=false
    username: root
    password: xjpdyx32.
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    #修改跳转的前缀和后缀,以下注释部分是spring boot的默认配置
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    #开发过程中需将缓存关闭
    cache: false
    check-template: false


