spring:
  application:
    name: bookhouse
server:
  port: 9100
eureka:
  client:
    service-url:
      defaultZone: http://xjp:xjp32.@localhost:8761/eureka/
#开启断路器
feign:
  hystrix:
    enabled: true
