server:
  port: 9999
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: http://localhost:8763/oauth/token
      user-authorization-uri: http://localhost:8763/oauth/authorize
    resource:
      user-info-uri: http://localhost:8763/user

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
